name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9   

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use a versão de Node.js que você está utilizando
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run predeploy script
        run: pnpm predeploy

      - name: Configure Git Email
        run: git config --global user.email "gsmaia23@gmail.com"

      - name: Configure Git Name 
        run: git config --global user.name "Gabriel-Souza-Maia"

      - name: Setup remote origin
        run: git remote set-url origin https://Gabriel-Souza-Maia:${{ secrets.MY_PASSWORD }}@github.com/Gabriel-Souza-Maia/pizza-shop-page-test.git

      - name: Run deploy script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm deploy
