name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9   

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use a versão de Node.js que você está utilizando
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run predeploy script
        run: pnpm predeploy

        run: git config --global user.email "gsmaia23@gmail.com"
        run: git config --global user.name "Gabriel-Souza-Maia"

      - name: Run deploy script
        run: pnpm deploy
